package com.re.paas.api.forms;

public enum InputType {
	HIDDEN, TEXT, EMAIL, SECRET, BOOLEAN, PHONE, DATE_OF_BIRTH, NUMBER, NUMBER_2L, NUMBER_3L, NUMBER_4L, AMOUNT, IMAGE, PLAIN, SIGNATURE, LANGUAGE, COUNTRY, ADDRESS, TERRITORY, CITY, PREFERED_LOCALE, TIMEZONE
}
