package com.re.paas.api.infra.database.document;

import static java.lang.annotation.RetentionPolicy.RUNTIME;

import java.lang.annotation.Retention;

@Retention(RUNTIME)
/**
 * This is used to specify that the primary key of a table can be generated if
 * no value is supplied
 * 
 * @author anthonyanyanwu
 *
 */
public @interface AutoGenerated {

}
