package com.re.paas.integrated.tables.defs.forms;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.re.paas.api.classes.ClientRBRef;
import com.re.paas.api.infra.database.document.AutoGenerated;
import com.re.paas.api.infra.database.model.IndexDefinition;
import com.re.paas.api.infra.database.model.IndexDescriptor.Type;
import com.re.paas.api.infra.database.model.Projection;
import com.re.paas.api.infra.database.modelling.BaseTable;
import com.re.paas.integrated.tables.spec.forms.FormSectionTableSpec;

public class FormSectionTable implements BaseTable {

	@AutoGenerated
	String id;
	
	ClientRBRef title;
	Integer type;
	ClientRBRef description;
	String realm;
	Date dateCreated;

	@Override
	public String hashKey() {
		return FormSectionTableSpec.ID;
	}

	@Override
	public List<IndexDefinition> indexes() {
		List<IndexDefinition> indexes = new ArrayList<>();

		IndexDefinition typeIndex = new IndexDefinition(FormSectionTableSpec.TYPE_INDEX, Type.GSI)
				.setQueryOptimzed(true).addHashKey(FormSectionTableSpec.TYPE)
				.withProjection(new Projection().withNonKeyAttributes(FormSectionTableSpec.REALM));
		
		indexes.add(typeIndex);

		return indexes;
	}
}
