package com.re.paas.integrated.tables.defs.forms;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;

import com.re.paas.api.infra.database.document.AutoGenerated;
import com.re.paas.api.infra.database.model.IndexDefinition;
import com.re.paas.api.infra.database.model.IndexDescriptor.Type;
import com.re.paas.api.infra.database.modelling.BaseTable;
import com.re.paas.integrated.tables.spec.forms.FormCompositeFieldTableSpec;

public class FormCompositeFieldTable implements BaseTable {
	
	@AutoGenerated
	String id;
	
	String title;
	String section;
	String context;
	
	Integer sortOrder;
	Boolean isVisible;
	Boolean isRequired;
	Boolean isDefault;
	
	Date dateCreated;
	
	Boolean allowMultipleChoice;
	
	Map<String, String> options;
	
	String itemsSource;
	List<String> defaultSelections;
	
	@Override
	public String hashKey() {
		return FormCompositeFieldTableSpec.ID;
	}
	
	@Override
	public List<IndexDefinition> indexes() {
		List<IndexDefinition> indexes = new ArrayList<>();
		
		IndexDefinition sectionIndex = new IndexDefinition(FormCompositeFieldTableSpec.SECTION_INDEX, Type.GSI)
		.addHashKey(FormCompositeFieldTableSpec.SECTION);

		indexes.add(sectionIndex);
		
		return indexes;
	}
	
}
